image_pil:
  - type: HorizontalFlip
    prob: 0.5
  - type: RandomResizedCrop
    prob: 1.0
    size: 28
    scale: [0.2, 1.]
  - type: HorizontalFlip
    prob: 0.5
  - type: ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.1
    prob: 0.8
image_pil_default_transform:
  - type: ToTensor
  - type: Normalize
    mean: [0.1307]
    std: [0.3081]
  - type: Reshape2D
    h_dim: 1 # num_channels
    w_dim: 784  #32 x 32 x 3
