supervised_task_preprocessing:
  module: SupervisedTaskPreprocessing # this is the UID
  inputs: [[_input_, inputs]]
text_pre_encoder:
  module: TextPreEncoder
  inputs: [[supervised_task_preprocessing, text]]
text_encoder:
  module: TextEncoder
  inputs: [[text_pre_encoder, 0]] # for pre_encoders :=> 0: input, 1: target pre encoding
classifier:
  module: Classifier
  inputs: [[text_encoder, 0]]
