supervised_task_preprocessing:
  module: SupervisedTaskPreprocessing # this is the UID
  inputs: [[_input_, inputs]]
image_pre_encoder:
  module: ImagePreEncoder
  inputs: [[supervised_task_preprocessing, image]]
image_encoder:
  module: ImageEncoder
  inputs: [[image_pre_encoder, 0]] # for pre_encoders :=> 0: input, 1: target pre encoding
image_view_select_0:
  module: ViewSelect0
  inputs: [[image_encoder, 0]]
image_view_select_1:
  module: ViewSelect1
  inputs: [[image_encoder, 0]]
