gpus: 1 # set `1` to train on GPU, `0` to train on CPU only
accumulate_grad_batches: 1
max_epochs: 200
gradient_clip_val: 0.0
log_every_n_steps: 10
limit_train_batches: 1.0  # train on full dataset, can be used to toggle quick run
limit_val_batches: 1.0  # train on full dataset, can be used to toggle quick run
weights_summary: top # Set to 'full' to see every layer
progress_bar_refresh_rate: 1
track_grad_norm: -1 # Set to 2 to track norms of gradients
resume_from_checkpoint: null
reload_dataloaders_every_n_epochs: 1
