defaults:
  - task_flow: supcon_autoencoder_joint_classification
  - loss@losses.classifier_loss: classifier_loss
  - metric@metrics.accuracy: accuracy

task_weight: 1.0
torchmetrics: {}
callbacks: {}
