defaults:
  - /preprocessor@preprocessors.SupervisedTaskPreprocessing: supervised_task_preprocessing
  - /embedding@embeddings.ImagePreEncoderSup: square_patch
  - /embedding@embeddings.ImagePreEncoderAuto: square_patch
  - /encoder@encoders.ImageEncoderSup: transformer
  - /encoder@encoders.ImageEncoderAuto: transformer
  - /decoder@decoders.Grayscale: grayscale
  - /decoder@decoders.Classifier: classifier
  - /decoder@decoders.ViewSelect0: view_select
  - /decoder@decoders.ViewSelect1: view_select
  - /decoder@decoders.ImageDecoder: resnet18decoder
  - /decoder@decoders.ImageReshape: image_reshape
  - /loss@losses.ClassifierLoss: label_smoothing
  - /loss@losses.ContrastiveLoss: contrastive_loss
  - /loss@losses.MSELoss: mse_loss

train: True
label_smoothing: True

embeddings:
  ImagePreEncoderSup:
    d_model: 256
  ImagePreEncoderAuto:
    d_model: 256

encoders:
  ImageEncoderSup:
    d_model: 256
  ImageEncoderAuto:
    d_model: 256

decoders:
  ViewSelect0:
    n_views: 2
    view_idx: 0
  ViewSelect1:
    n_views: 2
    view_idx: 1
  Classifier: 
    d_input: 512
  ImageDecoder:
    d_input: 256
    input_height: 32
  ImageReshape:
    d_input: 1024
    output_height: 32
    output_width: 32

losses:
  ContrastiveLoss:
    module: sup_con
    type: sup_con
