defaults:
  - /preprocessor@preprocessors.SupervisedTaskPreprocessing: supervised_task_preprocessing
  - /embedding@embeddings.ImagePreEncoder: square_patch
  - /encoder@encoders.ImageEncoder: transformer
  - /decoder@decoders.Classifier: classifier
  - /decoder@decoders.Grayscale: grayscale
  - /decoder@decoders.ImageDecoder: resnet18decoder
  - /decoder@decoders.ImageReshape: image_reshape
  - /loss@losses.ClassifierLoss: label_smoothing
  - /loss@losses.MSELoss: mse_loss

train: True
label_smoothing: True

embeddings:
  ImagePreEncoder:
    d_model: 256

encoders:
  ImageEncoder:
    d_model: 256

decoders:
  Classifier: 
    d_input: 256
  ImageDecoder:
    d_input: 256
    input_height: 32
  ImageReshape:
    d_input: 1024
    output_height: 32
    output_width: 32

